### ISSUE TITLE
Move this repo

### ISSUE THREAD

**Issue by pesehr** [aoacademy/LetsGo#2]
@1995parham What do you think?
I suggest that create an organication for teaching projects and move this project there.

**Comment by 1995parham** [comment]
By repo you mean organization, I am right?

**Comment by pesehr** [comment]
Yes, edited

**Comment by 1995parham** [comment]
Ok, it sounds great. Do you have any idea about its name? something like ATern? ITern?

**Comment by pesehr** [comment]
AoAcademi

**Comment by 1995parham** [comment]
You the greatest namer whoever born 😄
